### ISSUE TITLE
APP: Zaprojektowanie wyglądu programu

### ISSUE THREAD

**Issue by maciekzam** [ISK-2015/projekt-zespolowy#11]
Proszę o zaprojektowanie ogólnego wyglądu programu jakie będą guziki jak rozmieszczone.
Technika dowolna. Chciałbym zobaczyć jak nasz program może wyglądać.

**Comment by zuowieszczy** [comment]
Powiedzmy że to już wstępnie zrobione ;) Do wykorzystania są ikonki z zestawu DefaultIcon, który jest na licencji Creative Common :)
