### ISSUE TITLE
WEB: Zaprojektowanie ogólnego działania strony

### ISSUE THREAD

**Issue by maciekzam** [ISK-2015/projekt-zespolowy#14]
Proszę o zaprojektowanie ogólnego działania strony. Czyli co będzie w poszczególnych zakładkach. Technika dowolna. Najchętniej jakiś word z opisami bądź projekt w visio opisujący zależności.

**Comment by kajdanlukasz** [comment]
nie posiadam Visio ;> Word'a, też nie ;> stworze plik tekstowy w którym opisze jak to widze, mam to wrzucić do folderu WEB?

**Comment by dematteusz** [comment]
Plik tekstowy może być mało czytelny. Visio mamy dostępne na msdn. Ostatecznie możesz skorzystać z libre office.

**Comment by esse** [comment]
polecam:
http://www.axure.com - kobyła
https://balsamiq.com - miłe, lekkie narzędzie do mockupów

**Comment by kajdanlukasz** [comment]
dziękuje za link do balsamiq, użyłem tego oprogramowania
Maciek, wrzuciłem właśnie mockup który udało mi sie zrobić (prosze o sprawdzenie i wyrozumiałość, pierwszy raz robie takie coś, tak samo jak i całą strone ;) jak zatwierdzisz, to Marcin z Adamem ruszą z pracami)

**Comment by esse** [comment]
@kajdanlukasz gdzie można podejrzeć te mockupy? :)

**Comment by maciekzam** [comment]
@esse po zrobienie git pull można znaleźć w folderze WEB plik videorent.pdf - to jest wykonany przez Łukasza mockup. 
Łukasz jak na mój gust i Twój pierwszy raz jest całkiem nieźle - mając na myśli schematy i szablony dokładnie o to mi chodziło.
