### ISSUE TITLE
Stworzenie loga dla movie4you

### ISSUE THREAD

**Issue by maciekzam** [ISK-2015/projekt-zespolowy#15]
Zaprojektowanie jakiegoś fajnego loga dla naszej strony. Mateusz D. zgłosiłeś chęć wykonania takiego zadania - więc jest Twoje.

**Comment by zuowieszczy** [comment]
Są jakieś propozycje, więc można zamknąć :)

**Comment by kajdanlukasz** [comment]
będzie bez loga, bo mi tak wizualnie do strony pasuje ;>
