### ISSUE TITLE
Zadbanie o szatę graficzną na naszej strony

### ISSUE THREAD

**Issue by maciekzam** [ISK-2015/projekt-zespolowy#17]
Potrzebujemy koncepcji na grafiki strony, kolory, czcionki. Tutaj mam problem - nie wiem kto z was i w jakim stopniu zajmuję się grafiką i chciałby się tym zająć ? 
Mogą to być 2-3 osoby z różnych podzespołów.
Moja propozycja
Mateusz D. - wydaje mi się czy lubisz graficznie trochę się bawić ? Bo zastanawiam się czy Tobie tego nie dać. Łukasz i Marcin - wy dobrze się w tym czujecie ? Może we 3 coś wymyślicie ? 

Zadanie otwarte - jeśli będzie więcej niż jedna osoba chciała się tym zająć sklonuje zadanie i przydzielę każdemu. Prośba o informację zwrotną.

**Comment by dematteusz** [comment]
Mogę wziąć ten temat razem z Marcinem, mam dostęp do dużej ilości grafik, które legalnie :) można wykorzystać.

**Comment by maciekzam** [comment]
Panowie - zostawiam to wam 3 - Łukasz też się zaangażuje tak myślę :)

**Comment by kajdanlukasz** [comment]
Jasne, tylko jeszcze nie w tym tygodniu, zajęty jestem teraz bardzo, ale od przyszłego tygodnia, rusze z poprawkami

**Comment by hornowski92** [comment]
grafiki już mam :) nie wiem co z logiem  strony
