### ISSUE TITLE
Pytanie do wszystkich : Szyfrowanie danych użytkowników

### ISSUE THREAD

**Issue by maciekzam** [ISK-2015/projekt-zespolowy#19]
Proszę o jakiś opis kogoś kto jest obeznany w temacie - jak powinien wyglądać proces zabezpieczenia danych użytkowników. Sytuacja - gość rejestruje się na naszej stronie - co dalej dzieje się z jego danymi gdzie są przechowywane i w jaki sposób zabepieczone ( Szyfrowanie, token itp). Może ktoś tutaj w komentarzach opisać proces zabezpieczania danych co kolejno się dzieje ?

**Comment by zuowieszczy** [comment]
Hasła haszujesz conajmniej MD5. Lepszy jest SHA-1, jeszcze lepszy SHA-2 (SHA-256), a najlepszy SHA-3, ale mogą być problemy z jego implementacją. Myślę że na nasze potrzeby wystarczy i MD5. Tak samo można zahaszować kod CCV2 z karty kredytowej. I w bazie przechowujesz tylko hasze, przy logowaniu hasło wpisane przez użytkownika się też haszuje i porównuje hasze.

Resztę danych, jak PESELE, numery dowodów, adresy, można szyfrować albo szyfrem symetrycznym (np DES albo asymetrycznym AES). Ale to jest trudniejsze w poprawnej i sensownej implementacji. A zapisanie hasła na sztywno w kodzie to tak jakbyś zamknął drzwi wejściowe na 4 zamki a klucze schował pod wycieraczką ;)

**Comment by kajdanlukasz** [comment]
Marcin z tym walczy, ale haszowanie już ogarnął, będziemy mieli hasło w MD5
