### ISSUE TITLE
WEB: Wykonanie szablonu strony

### ISSUE THREAD

**Issue by maciekzam** [ISK-2015/projekt-zespolowy#2]
Proszę o wykonanie ogólnego szablonu strony.  Zadanie polega na stworzeniu podstawowej strony html na której znajdzie się zarys naszej stronki. Czyli będzie strona główna z podziałem na menu. W menu moga być odwołania do pustych stron. Chodzi o podstawy - utworzenie plików index.html, folderów do css'a i inne. Cały grunt pod naszą stronę. Grafiki jakies podstawowe.

**Comment by kajdanlukasz** [comment]
Maciek sprawdź czy o to Ci chodziło? szkielet podstron, Adam i Marcin mogą już robić swoje zadania
