### ISSUE TITLE
WEB: Wykonanie podstrony katalog wraz z modułami sortującymi

### ISSUE THREAD

**Issue by maciekzam** [ISK-2015/projekt-zespolowy#21]
Wykonanie podstrony katalog. W katalogu powinna być cała baza filmów z możliwościami posortowania filmów po kilku opcjach. Póki nie będzie tam pełnej bazy filmów, prosze o wykonanie kilku przykładowych wpisów. 
Sorotowanie powinno być możliwe po każdej kolumnie ( Tytuł, rok, gatunek itp. ) Sorotowanie musi działać w 2 strony - od A od Z i na odwrót jak klikniemy jeszcze raz w ten sam nagłówek. Oczywiście powinno to też działać na cyfrach od najmniejszej do największej i w drugą stronę. Tworzyłem kiedyś podobny moduł sortujący w java script - więc udostępnie go - przerobienie pod nasze wymogi nie będzie lekkie ale do zrobienia.

**Comment by mswiders1** [comment]
Podobno najszybciej w ajaksie sie robi sortowanie ;))
No i możliwość sortowania z dwoma warunkami np najnowszy z najlepszymi
ocenami

**Comment by kajdanlukasz** [comment]
gotowe
