### ISSUE TITLE
WEB: Import z bazy produktów na stronę 

### ISSUE THREAD

**Issue by maciekzam** [ISK-2015/projekt-zespolowy#24]
Proszę o podpięcie na stronie bazę produktów.
Niebawem bazy powinny być gotowe - w razie pytań o bazę proszę pisać do Michała lub Mateusza.

**Comment by kajdanlukasz** [comment]
poczekam na baze i sie tym zajme

**Comment by kajdanlukasz** [comment]
Maciek, zwiększ czas oddania, za mało nam płacisz, żebyśmy kodowali w święta ;>

**Comment by kajdanlukasz** [comment]
update, żeby nie było że nic nie robię
zrobiłem dla jednego filmu, zapytania elegancko działają, tylko muszę się nauczyć jak to na pętle przerobić więc może mi to kilka dni zająć

**Comment by kajdanlukasz** [comment]
zacząłem to robić, ale baza coś sie krzaczy, więc czekam aż chłopaki poprawią, ale ogólnie działa
