### ISSUE TITLE
WEB: Poprawienie zakładki kontakt

### ISSUE THREAD

**Issue by maciekzam** [ISK-2015/projekt-zespolowy#27]
Proszę o poprawienie zakładki kontakt tak aby wyglądała bardziej profesjonalnie i zgodnie z obecnymi schematami wyglądu strony. 

Proszę też o zebranie i wpisanie danych kontaktowych wszystkich członków zespołu.

**Comment by kajdanlukasz** [comment]
Adam nam zedytował kontakt i cennik przez FTP'a, na stronie działa, jak będzie miał czas to wrzuci to tutaj
