### ISSUE TITLE
WEB: Znalezienie darmowej domeny pod stronę

### ISSUE THREAD

**Issue by maciekzam** [ISK-2015/projekt-zespolowy#3]
Musimy znaleźć jakąś darmową ( bądź płatną jeśli ktoś ma ochotę ) domenę. Nasza strona internetowa uważam, że powinna być wystawiona na świat więc musimy coś takiego znaleźć. Zadanie polega na założeniu domeny pod nazwę naszej wypożaczalni.  

Zadanie do wykonania po wymyśleniu nazwy naszej wypożyczalni.

**Comment by kajdanlukasz** [comment]
zrobione ( ͡° ͜ʖ ͡°)
