### ISSUE TITLE
Zadanie dla wszystkich: Nazwa naszej wypożyczalni

### ISSUE THREAD

**Issue by maciekzam** [ISK-2015/projekt-zespolowy#4]
Wrzucajcie w komentarzach tego zadania pomysły na nazwę naszej wypożyczalni. Sprawdźcie czy jest wolna taka domena jak wasz pomysł. 

Obowiązkowo każdy wrzuca min.1 swoją propozycję nazwy!

**Comment by kajdanlukasz** [comment]
"videorent" już tak na stronie w 3 miejscach napisałem... musi być :P

**Comment by patrykk91** [comment]
Maciek ciężko stwierdzić czy nasza propozycja będzie miała wolną domenę bo jeszcze nie wiadomo w jakiej domenie będziemy to robić :)

**Comment by maciekzam** [comment]
Patryk - ok - więc wymyślajcie na razie to słowo klucz, które będzie nazwą naszej wypożyczalni :)

**Comment by mjechna** [comment]
Jestem za nazwą videorent

**Comment by maciekzam** [comment]
panowie videorent.pl - jest już zarezerwowana jako alias - po kliknieciu przenosi nas jakąś stronę ze sprzetem do wypożyczenia :) Może coś bardziej kreatywnego ;) moja propozycje:  movietime.pl ;)

**Comment by dematteusz** [comment]
Ja proponuję: movie4you.pl

**Comment by kajdanlukasz** [comment]
może zmienić pl na coś innego, jest bardzo dużo opcji... poza tym, po co chcecie płacić za domene? nie idźmy tą drogą, niech to działa lokalnie ;> i tak na tym nie zarobimy, zepsuje wam marzenia, ani facebook, ani microsoft, ani apple, ani amazon, ani google nas nie podkupi za miliard złotych :P

**Comment by mswiders1** [comment]
A nie wygodniej zrobić lokalnie i na sql lite ? Tak żeby prowadzący mógł
uruchomić lokalnie bez komunikacji z zewnętrznymi zasobami ? Myśle ze
domena i hostowane baza to przerost firmy nad treścią

**Comment by kajdanlukasz** [comment]
no lepiej lokalnie, nie wiem po co tyle zachodu z tą domeną i nazwą

**Comment by mswiders1** [comment]
Zakopujemy sie juz na samym początku

**Comment by maciekzam** [comment]
Panowie zachęcam was mimo wszystko do lekkiego zaangażowania - macie okazję zrobić coś fajnego i działającego, macie okazję popracować zespołowo - a w dobrze zgranym zespole jest siła. Dlatego nie traktujcie tego jak kolejnego zaliczenia do odbębnienia i nie idzicie po najniższej linii oporu - jeśli macie szansę trochę się wykazać i zrobić coś fajnego - zróbcie to. Każdy ma trochę inną działkę do zrobienia każdy może coś z tego wynieść i czegoś się nauczyć - za pewne zauważyliście już, że jeśli sami się czegoś nie nauczycie - to nikt was nie nauczy - więc wykorzystajcie ten czas mądrze i nie róbcie na odwal. 

Dlatego według pierwotnych postanowień powstanie strona wystawiona na świat - nie będziemy płacić za hosting Michał już założył na cba darmową domenę wybraliśmy. Nim wy napisaliście komentarz negujący początkowe postanowienia on już to zrobił.

Panowie prośba - trochę zaangażowania i nie wszystko oby jak najprościej! 
Pozdrawiam!

**Comment by kajdanlukasz** [comment]
nie jest z Ciebie dobry coach ;p skoro już gotowe, pozmieniam nazwy w plikach i żeby nie było, przykładam sie ;> no to już mamy nazwe i hosting, temat do zamknięcia ;>
i jak to mówi poeta "skończmy te wojne polskie polskie"

**Comment by hornowski92** [comment]
cba to był mój pomysł :)

**Comment by kajdanlukasz** [comment]
jakie cba, ja tam nic nie przyjmowałem, pewnie Maciek łapówek nabrał
